### ISSUE TITLE
データベース接続の設定

### ISSUE THREAD

**Issue by udonrm** [udonrm/php-todoApp#3]

**Comment by riku-miyawaki** [comment]
```
<?php
$host = "";
$port = "";
$dbname = "";
$user = "";
$password = "";

try {
    $db = "pgsql:host=$host;port=$port;dbname=$dbname;user=$user;password=$password";
    $conn = new PDO($db);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Connection failed: " . $e->getMessage());
}
```

**Comment by udonrm** [comment]
- Add phpdotenv to composer https://github.com/vlucas/phpdotenv
- [PHP: Magic Constants - Manual](https://www.php.net/manual/ja/language.constants.magic.php) 
スクリプトの実行場所に依存せずに正しくファイルを読み込める
- [PHP: include_once - Manual](https://www.php.net/manual/ja/function.include-once.php)
